
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class CurrentCardOptions extends javax.swing.JFrame {
    
    private PropertyCard currentCard;
    private Player currentPlayer;
    
    public CurrentCardOptions(PropertyCard card,Player player) {
        
        this.currentCard = card;
        this.currentPlayer = player;
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        if(card.getOwner() == null){
            ownedPanel.setVisible(false);
            unownedPanel.setVisible(true);
            
            
        }
        else if(card.getOwner().equals(currentPlayer)){
            this.dispose();
            JOptionPane.showMessageDialog(null, "This property card belongs to you");
            
            
        }
        else{
            ownedPanel.setVisible(true);
            unownedPanel.setVisible(false);
            ownerName.setText("This card belongs to player " + card.getOwner().getName());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ownedPanel = new javax.swing.JPanel();
        photoOfCard = new javax.swing.JLabel();
        ownerName = new javax.swing.JLabel();
        payRent = new javax.swing.JButton();
        unownedPanel = new javax.swing.JPanel();
        photoOfCard2 = new javax.swing.JLabel();
        unownedText = new javax.swing.JLabel();
        buyCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        photoOfCard.setText("photo of card");

        ownerName.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        ownerName.setText("This card belongs to");

        payRent.setText("Pay Rent");
        payRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payRentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ownedPanelLayout = new javax.swing.GroupLayout(ownedPanel);
        ownedPanel.setLayout(ownedPanelLayout);
        ownedPanelLayout.setHorizontalGroup(
            ownedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownedPanelLayout.createSequentialGroup()
                .addComponent(photoOfCard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ownerName)
                .addGap(0, 163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ownedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payRent, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        ownedPanelLayout.setVerticalGroup(
            ownedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownedPanelLayout.createSequentialGroup()
                .addComponent(photoOfCard)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ownedPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ownerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(payRent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        photoOfCard2.setText("photo of card");

        unownedText.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        unownedText.setText("This card is unowned");

        buyCard.setText("Buy");
        buyCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unownedPanelLayout = new javax.swing.GroupLayout(unownedPanel);
        unownedPanel.setLayout(unownedPanelLayout);
        unownedPanelLayout.setHorizontalGroup(
            unownedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unownedPanelLayout.createSequentialGroup()
                .addGroup(unownedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(unownedPanelLayout.createSequentialGroup()
                        .addComponent(photoOfCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(unownedText)))
                .addGap(0, 92, Short.MAX_VALUE))
        );
        unownedPanelLayout.setVerticalGroup(
            unownedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unownedPanelLayout.createSequentialGroup()
                .addComponent(photoOfCard2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(unownedPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(unownedText)
                .addGap(139, 139, 139)
                .addComponent(buyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(ownedPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(unownedPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ownedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(unownedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ownedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(unownedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRentActionPerformed
        // TODO add your handling code here:
        
        if(currentPlayer.payPlayer(currentCard.getOwner(),currentCard.calculateCharge())){
            JOptionPane.showMessageDialog(null, "Rent paid succesfully");
            this.dispose();
        }
        else{
            this.dispose();
            ManageCards managecards = new ManageCards(currentPlayer.getCards(),currentPlayer);
            
            
        }
      
    }//GEN-LAST:event_payRentActionPerformed

    private void buyCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyCardActionPerformed
        // TODO add your handling code here:
        if(currentPlayer.buyCard(currentCard)){
        JOptionPane.showMessageDialog(null, "Card bought sucessfully");
        this.dispose();
        }
        
        
    }//GEN-LAST:event_buyCardActionPerformed

    
    

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyCard;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel ownedPanel;
    private javax.swing.JLabel ownerName;
    private javax.swing.JButton payRent;
    private javax.swing.JLabel photoOfCard;
    private javax.swing.JLabel photoOfCard2;
    private javax.swing.JPanel unownedPanel;
    private javax.swing.JLabel unownedText;
    // End of variables declaration//GEN-END:variables
}
